---
title: "TSA Final Project Data Cleanup"
author: "Angela Zeng, Kristen Trinh, Eliza Henderson"
output:
  html_document:
    df_print: paged
  pdf_document: default
geometry: margin=2.54cm
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,tidy.opts=list(width.cutoff=80), tidy=FALSE) 
```

## Set up
```{r message=FALSE}
#Load libraries 
library(tidyverse)
```

##Import and process data 
```{r}
#import dataset 
df <- read.csv(file="./Data/ERCOT_annual_generation_data.csv", header = T, dec = ".", sep=",",stringsAsFactors = F) 

#extract appropriate rows and columns 
df<- df[,c(1,3:(ncol(df)-1))]
df<- df%>%
  filter(Year <= 2022)

#pivot_wider
df2<- df%>% 
  pivot_wider(names_from = c(Year), values_from = c(Jan, Feb, Mar, Apr,May,Jun,
                                                    Jul, Aug, Sep,Oct, Nov, Dec))
#transpose and fix row and column names 
tdf2<- t(df2)
df2<- as.data.frame(tdf2)
rm(tdf2)
colnames(df2)<- df2[1,]
df2<- df2[2:nrow(df2),]
df2$date<- rownames(df2)
rownames(df2)<- NULL

#process date column 
df2<- df2[,c(ncol(df2),1:(ncol(df2)-1))]
date<-strsplit(df2$date,split="_")
date<-as.data.frame(matrix(unlist(date),ncol=2,byrow=T))
date<- my(paste(date$V1, date$V2))
df2$date<- date
rm(date)

#fixing the two wind columns 
df2$Wind<- ifelse(is.na(df2$Wind), df2$Wnd, df2$Wind)
df2<- subset(df2, select=-c(Wnd))
```

##SCRAP CODE
```{r}
#try pivot_longer on og data 
df3<- df %>%
  pivot_longer(!c(Fuel.Totals, Year), names_to = "Months", values_to = "MWh")
```

